"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type * as THREE from "three";
import React, { type JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

const url = "/models/staff.glb";

useGLTF.preload(url);

type GLTFResult = GLTF & {
  nodes: {
    Wizard_Staff3_Wizard_Staff3_0: THREE.Mesh;
    Wizard_Staff3_Wizard_Staff3_0_1: THREE.Mesh;
    Wizard_Staff3_Wizard_Staff3_0_2: THREE.Mesh;
    Wizard_Staff3_Wizard_Staff3_0_3: THREE.Mesh;
    Wizard_Staff2_Wizard_Staff2_0: THREE.Mesh;
  };
  materials: {
    Wizard_Staff3: THREE.MeshStandardMaterial;
    Wizard_Staff2: THREE.MeshStandardMaterial;
  };
};

export function Staff(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(url) as unknown as GLTFResult;

  const modelRef = useRef<THREE.Group>(null);

  useFrame(() => {
    if (!modelRef.current) return;
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group
      {...props}
      ref={modelRef}
      dispose={null}
      position={[0, -2, 0]}
      scale={[3, 3, 3]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wizard_Staff3_Wizard_Staff3_0.geometry}
        material={materials.Wizard_Staff3}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wizard_Staff3_Wizard_Staff3_0_1.geometry}
        material={materials.Wizard_Staff3}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wizard_Staff3_Wizard_Staff3_0_2.geometry}
        material={materials.Wizard_Staff3}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wizard_Staff3_Wizard_Staff3_0_3.geometry}
        material={materials.Wizard_Staff3}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wizard_Staff2_Wizard_Staff2_0.geometry}
        material={materials.Wizard_Staff2}
        position={[-0.041, 0.983, 0.768]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.04}
      />
    </group>
  );
}
