name: Quality

on:
  push:
    branches: [main]
    paths:
      - "**/*.tsx"
      - "**/*.ts"
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.css"
      - "**/*.json"
      - ".github/workflows/setup-node.yml"
      - ".github/actions/quality.yml"

env:
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_CACHE: "remote:rw"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-node

      - name: Run check tasks with Turbo
        run: |
          pnpm turbo lint check-types
